/**
 * File System Service for Agent Code Generation
 *
 * Creates structured project files on VPS for agents to write code.
 * Each run gets its own directory under /workspace/projects/{runId}/
 */

import { promises as fs } from 'fs'
import * as path from 'path'
import Logger from '#app/utils/logger'

const WORKSPACE_ROOT = process.env.WORKSPACE_ROOT || '/home/xfajarr/.openclaw/workspace/claw-cartel-projects'

export interface FileNode {
  name: string
  type: 'file' | 'directory'
  path: string
  size?: number
  children?: FileNode[]
}

export interface FileChangeEvent {
  runId: string
  action: 'created' | 'modified' | 'deleted'
  filePath: string
  content?: string
  agentName: string
  timestamp: string
}

class FileSystemService {
  constructor() {
    // Ensure workspace root exists
    this.ensureWorkspaceRoot()
  }

  private async ensureWorkspaceRoot(): Promise<void> {
    try {
      await fs.mkdir(WORKSPACE_ROOT, { recursive: true })
    } catch (error) {
      Logger.error({ error, WORKSPACE_ROOT }, 'Failed to create workspace root')
    }
  }

  /**
   * Initialize project directory structure for a run
   */
  async initProject(runId: string, projectName: string): Promise<string> {
    // Ensure workspace root exists
    await fs.mkdir(WORKSPACE_ROOT, { recursive: true })

    const projectPath = path.join(WORKSPACE_ROOT, runId)

    const structure = [
      'research',
      'design',
      'backend/src/api',
      'backend/src/models',
      'backend/src/contracts',
      'backend/tests',
      'frontend/src/components',
      'frontend/src/pages',
      'frontend/src/hooks',
      'frontend/src/utils',
      'frontend/public',
      'deployment',
      'docs',
    ]

    for (const dir of structure) {
      await fs.mkdir(path.join(projectPath, dir), { recursive: true })
    }

    // Create initial README
    await this.writeFile(runId, 'README.md', `# ${projectName}

Generated by ClawCartel AI Agent Squad
Run ID: ${runId}

## Project Structure

- \`research/\` - Market research and analysis
- \`design/\` - UI/UX specifications and design docs
- \`backend/\` - Backend API and smart contracts
- \`frontend/\` - Frontend application
- \`deployment/\` - Deployment scripts and configs
- \`docs/\` - Additional documentation

## Agents

- 📋 PM - Project coordination
- 🔬 Researcher - Market analysis
- 🎨 FE - Frontend development  
- ⚙️ BE_SC - Backend & smart contracts
`, 'PM')

    Logger.info({ runId, projectPath }, 'Project initialized')

    return projectPath
  }

  /**
   * Write file to project directory
   */
  async writeFile(
    runId: string,
    filePath: string,
    content: string,
    agentName: string
  ): Promise<FileChangeEvent> {
    const fullPath = path.join(WORKSPACE_ROOT, runId, filePath)
    const dir = path.dirname(fullPath)

    // Ensure directory exists
    await fs.mkdir(dir, { recursive: true })

    // Check if file exists (for event type)
    let action: 'created' | 'modified' = 'created'
    try {
      await fs.access(fullPath)
      action = 'modified'
    } catch {
      // File doesn't exist, keep as 'created'
    }

    // Write file
    await fs.writeFile(fullPath, content, 'utf-8')

    Logger.info({ runId, filePath, agent: agentName, action }, 'File written')

    return {
      runId,
      action,
      filePath,
      content: content.slice(0, 500), // Preview only
      agentName,
      timestamp: new Date().toISOString(),
    }
  }

  /**
   * Read file content
   */
  readFile(runId: string, filePath: string): Promise<string> {
    const fullPath = path.join(WORKSPACE_ROOT, runId, filePath)

    return fs.readFile(fullPath, 'utf-8')
  }

  /**
   * Check if file exists
   */
  async exists(runId: string, filePath: string): Promise<boolean> {
    try {
      await fs.access(path.join(WORKSPACE_ROOT, runId, filePath))

      return true
    } catch {
      return false
    }
  }

  /**
   * List directory structure
   */
  async listDirectory(runId: string, dirPath = ''): Promise<FileNode[]> {
    const fullPath = path.join(WORKSPACE_ROOT, runId, dirPath)

    try {
      const entries = await fs.readdir(fullPath, { withFileTypes: true })
      const nodes: FileNode[] = []

      for (const entry of entries) {
        const entryPath = path.join(dirPath, entry.name)

        if (entry.isDirectory()) {
          nodes.push({
            name: entry.name,
            type: 'directory',
            path: entryPath,
            children: await this.listDirectory(runId, entryPath),
          })
        } else {
          const stats = await fs.stat(path.join(fullPath, entry.name))
          nodes.push({
            name: entry.name,
            type: 'file',
            path: entryPath,
            size: stats.size,
          })
        }
      }

      return nodes.sort((a, b) => {
        // Directories first, then alphabetically
        if (a.type === b.type) return a.name.localeCompare(b.name)

        return a.type === 'directory' ? -1 : 1
      })
    } catch (error) {
      Logger.error({ runId, dirPath, error }, 'Failed to list directory')

      return []
    }
  }

  /**
   * Get all files as flat list
   */
  async getAllFiles(runId: string, dirPath = ''): Promise<string[]> {
    const fullPath = path.join(WORKSPACE_ROOT, runId, dirPath)
    const files: string[] = []

    try {
      const entries = await fs.readdir(fullPath, { withFileTypes: true })

      for (const entry of entries) {
        const entryPath = path.join(dirPath, entry.name)

        if (entry.isDirectory()) {
          files.push(...await this.getAllFiles(runId, entryPath))
        } else {
          files.push(entryPath)
        }
      }
    } catch {
      // Directory doesn't exist or can't read
    }

    return files
  }

  /**
   * Create zip archive of project
   */
  async createZip(runId: string): Promise<string> {
    const { exec } = await import('child_process')
    const { promisify } = await import('util')
    const execAsync = promisify(exec)

    const projectPath = path.join(WORKSPACE_ROOT, runId)
    const zipPath = path.join(WORKSPACE_ROOT, `${runId}.zip`)

    try {
      await execAsync(`cd "${projectPath}" && zip -r "${zipPath}" .`)
      Logger.info({ runId, zipPath }, 'Project zipped')

      return zipPath
    } catch (error) {
      Logger.error({ runId, error }, 'Failed to create zip')
      throw error
    }
  }

  /**
   * Delete project directory
   */
  async deleteProject(runId: string): Promise<void> {
    const projectPath = path.join(WORKSPACE_ROOT, runId)
    await fs.rm(projectPath, { recursive: true, force: true })
    Logger.info({ runId }, 'Project deleted')
  }

  /**
   * Get file stats
   */
  async getStats(runId: string): Promise<{
    totalFiles: number
    totalSize: number
    byAgent: Record<string, number>
  }> {
    const files = await this.getAllFiles(runId)
    let totalSize = 0
    const byAgent: Record<string, number> = {}

    for (const filePath of files) {
      try {
        const stats = await fs.stat(path.join(WORKSPACE_ROOT, runId, filePath))
        totalSize += stats.size
      } catch {
        // Skip unreadable files
      }
    }

    return {
      totalFiles: files.length,
      totalSize,
      byAgent,
    }
  }
}

export const fileSystem = new FileSystemService()
