import { chmodSync, mkdirSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import type { ToolHandler, ToolResult } from '#app/agents/skills/skill.types'

/**
 * generate_smart_contract — Sam scaffolds smart contracts.
 */
export const generateSmartContractHandler: ToolHandler = {
  name: 'generate_smart_contract',
  description: 'Generate Anchor/Solana smart contract scaffold',
  allowedRoles: ['be_sc'],
  producesFiles: true,

  async execute(params, context): Promise<ToolResult> {
    const rawName = (params.name as string) || 'basic_program'
    const name = rawName.trim().toLowerCase().replace(/[^a-z0-9_]/g, '_') || 'basic_program'
    const anchorDir = join(context.workspacePath, 'anchor')
    const programDir = join(anchorDir, 'programs', name)
    const contractDir = join(programDir, 'src')
    const scriptsDir = join(anchorDir, 'scripts')
    const testsDir = join(anchorDir, 'tests')
    const libRsPath = join(contractDir, 'lib.rs')
    const deployScriptPath = join(scriptsDir, 'deploy-devnet.sh')
    await Promise.resolve()

    const files: Array<{ path: string; content: string }> = [
      {
        path: join(anchorDir, 'Cargo.toml'),
        content: `[workspace]
members = ["programs/${name}"]
resolver = "2"

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1
`,
      },
      {
        path: join(anchorDir, 'Anchor.toml'),
        content: `[features]
resolution = true
skip-lint = false

[programs.devnet]
${name} = "11111111111111111111111111111111"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "anchor test"
deploy-devnet = "bash scripts/deploy-devnet.sh"
`,
      },
      {
        path: join(anchorDir, 'package.json'),
        content: `{
  "name": "${name}-anchor",
  "private": true,
  "version": "0.1.0",
  "scripts": {
    "build": "anchor build",
    "test": "anchor test",
    "deploy:devnet": "bash scripts/deploy-devnet.sh"
  },
  "devDependencies": {
    "@coral-xyz/anchor": "^0.30.1",
    "typescript": "^5.6.3"
  }
}
`,
      },
      {
        path: join(programDir, 'Cargo.toml'),
        content: `[package]
name = "${name}"
version = "0.1.0"
description = "Generated by ClawCartel BE_SC agent"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "${name}"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build"]

[dependencies]
anchor-lang = "0.30.1"
`,
      },
      {
        path: libRsPath,
        content: `use anchor_lang::prelude::*;

declare_id!("11111111111111111111111111111111");

#[program]
pub mod ${name} {
    use super::*;

    pub fn initialize(ctx: Context<Initialize>) -> Result<()> {
        let counter = &mut ctx.accounts.counter;
        counter.authority = ctx.accounts.authority.key();
        counter.count = 0;
        Ok(())
    }

    pub fn increment(ctx: Context<Increment>) -> Result<()> {
        let counter = &mut ctx.accounts.counter;
        require_keys_eq!(
            counter.authority,
            ctx.accounts.authority.key(),
            ErrorCode::Unauthorized
        );
        counter.count = counter
            .count
            .checked_add(1)
            .ok_or(ErrorCode::CounterOverflow)?;
        Ok(())
    }
}

#[derive(Accounts)]
pub struct Initialize<'info> {
    #[account(
        init,
        payer = authority,
        space = 8 + Counter::INIT_SPACE,
        seeds = [b"counter", authority.key().as_ref()],
        bump
    )]
    pub counter: Account<'info, Counter>,
    #[account(mut)]
    pub authority: Signer<'info>,
    pub system_program: Program<'info, System>,
}

#[derive(Accounts)]
pub struct Increment<'info> {
    #[account(
        mut,
        seeds = [b"counter", authority.key().as_ref()],
        bump
    )]
    pub counter: Account<'info, Counter>,
    pub authority: Signer<'info>,
}

#[account]
#[derive(InitSpace)]
pub struct Counter {
    pub authority: Pubkey,
    pub count: u64,
}

#[error_code]
pub enum ErrorCode {
    #[msg("Only counter authority can increment")]
    Unauthorized,
    #[msg("Counter overflow")]
    CounterOverflow,
}
`,
      },
      {
        path: join(programDir, 'src', 'instructions', 'mod.rs'),
        content: `// Instruction modules can be split out here as the program grows.
`,
      },
      {
        path: join(programDir, 'src', 'state', 'mod.rs'),
        content: `// State modules can be split out here as the program grows.
`,
      },
      {
        path: join(programDir, 'src', 'errors.rs'),
        content: `// Custom errors can be extracted here when needed.
`,
      },
      {
        path: join(testsDir, `${name}.ts`),
        content: `import * as anchor from "@coral-xyz/anchor";
import { Program } from "@coral-xyz/anchor";

describe("${name}", () => {
  anchor.setProvider(anchor.AnchorProvider.env());
  const program = anchor.workspace["${name}"] as Program;

  it("builds and is callable", async () => {
    const tx = await program.methods.initialize().rpc();
    console.log("initialize tx", tx);
  });
});
`,
      },
      {
        path: deployScriptPath,
        content: `#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

if ! command -v solana >/dev/null 2>&1; then
  echo "solana CLI is required. Install from https://docs.solana.com/cli/install-solana-cli-tools"
  exit 1
fi

if ! command -v anchor >/dev/null 2>&1; then
  echo "anchor CLI is required. Install from https://www.anchor-lang.com/docs/installation"
  exit 1
fi

echo "Setting Solana RPC to devnet..."
solana config set --url https://api.devnet.solana.com

WALLET_ADDRESS="$(solana address)"
echo "Using wallet: $WALLET_ADDRESS"
echo "Requesting airdrop (safe to ignore failure if rate-limited)..."
solana airdrop 2 "$WALLET_ADDRESS" || true

echo "Building program..."
anchor build

echo "Syncing program ids..."
anchor keys sync

echo "Deploying to devnet..."
anchor deploy --provider.cluster devnet

PROGRAM_ID="$(solana address -k target/deploy/${name}-keypair.json)"
echo "Deployed program id: $PROGRAM_ID"
`,
      },
      {
        path: join(anchorDir, 'README.md'),
        content: `# ${name} (Anchor Program)

Minimal deployable Solana program generated by BE_SC agent.

## What this program does
- \`initialize\`: creates a PDA counter account for authority
- \`increment\`: increments the authority-owned counter

## Prerequisites
- Rust + Cargo
- Solana CLI
- Anchor CLI
- Node.js (for TypeScript tests/scripts)

## Build
\`\`\`bash
cd anchor
npm install
npm run build
\`\`\`

## Deploy to Devnet
\`\`\`bash
cd anchor
npm run deploy:devnet
\`\`\`

The script will:
1. set RPC to devnet
2. airdrop SOL to your wallet
3. build
4. run \`anchor keys sync\`
5. deploy to devnet
`,
      },
    ]

    try {
      mkdirSync(contractDir, { recursive: true })
      mkdirSync(scriptsDir, { recursive: true })
      mkdirSync(testsDir, { recursive: true })

      for (const file of files) {
        const dir = file.path.substring(0, file.path.lastIndexOf('/'))
        if (dir) {
          mkdirSync(dir, { recursive: true })
        }
        writeFileSync(file.path, file.content, 'utf-8')
      }

      chmodSync(deployScriptPath, 0o755)

      return {
        success: true,
        data: {
          name,
          libRsPath,
          filesCreated: files.map(f => f.path),
          deployCommand: 'cd anchor && npm run deploy:devnet',
        },
      }
    } catch (error) {
      return {
        success: false,
        error: error instanceof Error ? error.message : 'Smart contract scaffold failed',
      }
    }
  },
}
