enum ErrorCodes {
  SYSTEM_ERROR = 'SYSTEM_ERROR',
  PARSING_ERROR = 'PARSING_ERROR',
  BAD_REQUEST = 'BAD_REQUEST',
  NOT_FOUND = 'NOT_FOUND',
  UNAUTHORIZED = 'UNAUTHORIZED',
  INVALID_CREDENTIAL = 'INVALID_CREDENTIAL',
}

export default ErrorCodes
