enum ErrorCodes {
  SYSTEM_ERROR = 'SYSTEM_ERROR',
  PARSING_ERROR = 'PARSING_ERROR',
  BAD_REQUEST = 'BAD_REQUEST',
  NOT_FOUND = 'NOT_FOUND',
  UNAUTHORIZED = 'UNAUTHORIZED',
  INVALID_CREDENTIAL = 'INVALID_CREDENTIAL',
  TOOLCHAIN_MISSING = 'TOOLCHAIN_MISSING',
  COMPILE_FAILED = 'COMPILE_FAILED',
  ARTIFACT_NOT_FOUND = 'ARTIFACT_NOT_FOUND',
  SESSION_EXPIRED = 'SESSION_EXPIRED',
  RPC_REJECTED = 'RPC_REJECTED',
}

export default ErrorCodes
